"""Create greetings table

Revision ID: 7e10840e1f67
Revises: 
Create Date: 2025-12-03 21:18:10.378599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e10840e1f67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('greetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('recipient_whatsapp', sa.String(), nullable=True),
    sa.Column('greeting_template_id', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ai_generated', sa.String(), nullable=True),
    sa.Column('delivery_channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_greetings_delivery_channel'), 'greetings', ['delivery_channel'], unique=False)
    op.create_index(op.f('ix_greetings_greeting_template_id'), 'greetings', ['greeting_template_id'], unique=False)
    op.create_index(op.f('ix_greetings_id'), 'greetings', ['id'], unique=False)
    op.create_index(op.f('ix_greetings_recipient_email'), 'greetings', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_greetings_recipient_whatsapp'), 'greetings', ['recipient_whatsapp'], unique=False)
    op.create_index(op.f('ix_greetings_sender_email'), 'greetings', ['sender_email'], unique=False)
    op.create_index(op.f('ix_greetings_sender_name'), 'greetings', ['sender_name'], unique=False)
    op.create_index(op.f('ix_greetings_status'), 'greetings', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_greetings_status'), table_name='greetings')
    op.drop_index(op.f('ix_greetings_sender_name'), table_name='greetings')
    op.drop_index(op.f('ix_greetings_sender_email'), table_name='greetings')
    op.drop_index(op.f('ix_greetings_recipient_whatsapp'), table_name='greetings')
    op.drop_index(op.f('ix_greetings_recipient_email'), table_name='greetings')
    op.drop_index(op.f('ix_greetings_id'), table_name='greetings')
    op.drop_index(op.f('ix_greetings_greeting_template_id'), table_name='greetings')
    op.drop_index(op.f('ix_greetings_delivery_channel'), table_name='greetings')
    op.drop_table('greetings')
    # ### end Alembic commands ###
